services:
  postgres:
    image: postgres:17
    container_name: alertini-postgres
    environment:
      POSTGRES_USER: alertini
      POSTGRES_PASSWORD: alertini
      POSTGRES_DB: alertini
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - alertini-network

networks:
  alertini-network:

volumes:
  pgdata:
